name: Hello World!
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]   
  repository_dispatch:
    types: [on-demand-test]      
jobs:
  echo-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Ecgi Environment Variables 
        if: ${{ runner.os == 'Linux' }}
        env:
          APP_VERSION: "1.0.0"
          RUNNER_CONTENT: ${{ runner.content }}
        run: |
           echo "This job trigeered by ${GITHUB_EVENT_NAME} event and the repository name is ${GITHUB_REPOSITORY}";
           echo "The workflow name is ${GITHUB_WORKFLOW} and the workflow run ID is ${GITHUB_RUN_ID}";
           echo "The workflow run number is ${GITHUB_RUN_NUMBER} and the job name is ${GITHUB_JOB}";
           echo "The actor who triggered the workflow is ${GITHUB_ACTOR} and the event name is ${GITHUB_EVENT_NAME}";
           echo "The event path is ${GITHUB_EVENT_PATH} and the workspace path is ${GITHUB_WORKSPACE}";
           echo "The server URL is ${GITHUB_SERVER_URL} and the API URL is ${GITHUB_API_URL}";
           echo "The GraphQL URL is ${GITHUB_GRAPHQL_URL} and the repository owner is ${GITHUB_REPOSITORY_OWNER}";
           echo "version of the application is ${APP_VERSION}";
           echo "The runner content is ${RUNNER_CONTENT}";
           echo "The Database password is ${secrets.DB_PASSWORD}";
  hello-job:
    if: ${{ github.event.client_payload.status != 'complated'  }}
    name: Test Job1
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello Github Actions! na"

      - name: Show payload from external trigger
        run: |
          echo "Trigger Event: ${{ github.event_name }}"
          echo "Client Payload Message: ${{ github.event.client_payload.message }}"
  
  Second-job:
    if: ${{ github.event_name != 'on-demand-test'  }}
    runs-on: widdows-latest
    needs: hello-job
    steps:
      - name: "Check runner OS and name" 
        run: echo "This job is running on ${RUNNER_OS} and the runner name is ${RUNNER_NAME}"
        if: ${{ runner_od == 'linux' }}      
