on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - staging
          - production
        default: "staging"
      run_ui_test:
        description: "Run UI tests before deployment"
        required: true
        type: boolean
        default: false
      run_test:
        description: "Run tests before deployment"
        required: true
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.set-status.outputs.status }}      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          repository: ${{ github.repository }}
          ref: ${{github.ref}}
          fetch-depth: 0
      - name: List files in the repository
        run: ls ${{github.workspace}}
      - name: set-status
        id: set-status
        run: |
         echo "Get result from building process"
         echo "status=success" >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    if: ${{ inputs.run_ui_test == true }}
    steps:
      - name: Ui Testing
        run: echo "Running UI tests... in ${{ inputs.environment }} environment"
 
